### ISSUE TITLE
str_replace casts to 'character'

### ISSUE THREAD

**Issue by gavin-kelly-1** [underthecurve/r-data-cleaning-tricks#1]
Prior to the text "It's still a factor, because we never told R that it should be numeric." in the README, the output is actually of class 'character'.  If it were still a factor, then the following 'as.numeric' would be a bug, as it would convert the first alphabetic entry to 1...  This could confuse beginners, who could assume the correct way to convert a factor to numeric would be 'as.numeric', rather than as.numeric(as.character(' which is possibly worth a mention anyway

**Comment by underthecurve** [comment]
thank you! I've fixed the typo for now. will think on including an example re: factors and `as.numeric(as.character)` later.
